name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    name: test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --verbose
    - name: Set path for candle and light
      run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $GITHUB_PATH
      shell: bash
    - name: Install cargo-wix
      run: cargo install cargo-wix
    - name: Build Installer
      run: cargo wix --nocapture --release
    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: windows-installer
        path: target/wix/*.msi
        retention: 30